// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

public class AddedNodeAddressInfo {
	/* ipAddress:port, if resolvable, the actual IP address */
	String address;
	/* true|false|inbound|outbound */
	String connected;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public AddedNodeAddressInfo() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getAddress() {
		return this.address;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getConnected() {
		return this.connected;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setAddress(final String address) {
		this.address = address;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setConnected(final String connected) {
		this.connected = connected;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof AddedNodeAddressInfo)) return false;
		final AddedNodeAddressInfo other = (AddedNodeAddressInfo)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$address = this.getAddress();
		final java.lang.Object other$address = other.getAddress();
		if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
		final java.lang.Object this$connected = this.getConnected();
		final java.lang.Object other$connected = other.getConnected();
		if (this$connected == null ? other$connected != null : !this$connected.equals(other$connected)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof AddedNodeAddressInfo;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $address = this.getAddress();
		result = result * PRIME + ($address == null ? 43 : $address.hashCode());
		final java.lang.Object $connected = this.getConnected();
		result = result * PRIME + ($connected == null ? 43 : $connected.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "AddedNodeAddressInfo(address=" + this.getAddress() + ", connected=" + this.getConnected() + ")";
	}
}