// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

import java.util.List;

public class AddressGroupings {
	List<AddressDetails> Groupings;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public AddressGroupings() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<AddressDetails> getGroupings() {
		return this.Groupings;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setGroupings(final List<AddressDetails> Groupings) {
		this.Groupings = Groupings;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof AddressGroupings)) return false;
		final AddressGroupings other = (AddressGroupings)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$Groupings = this.getGroupings();
		final java.lang.Object other$Groupings = other.getGroupings();
		if (this$Groupings == null ? other$Groupings != null : !this$Groupings.equals(other$Groupings)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof AddressGroupings;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $Groupings = this.getGroupings();
		result = result * PRIME + ($Groupings == null ? 43 : $Groupings.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "AddressGroupings(Groupings=" + this.getGroupings() + ")";
	}
}