// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

import java.util.List;

public class Catchup {
	
	/**
	 * supposedly, the header hash of the block at the requested depth
	 */
	private String lastblock;
	
	/**
	 * transactions affecting the wallet since the requested block
	 */
	private List<WalletTx> transactions;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Catchup() {
	}

	/**
	 * supposedly, the header hash of the block at the requested depth
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getLastblock() {
		return this.lastblock;
	}

	/**
	 * transactions affecting the wallet since the requested block
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public List<WalletTx> getTransactions() {
		return this.transactions;
	}

	/**
	 * supposedly, the header hash of the block at the requested depth
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setLastblock(final String lastblock) {
		this.lastblock = lastblock;
	}

	/**
	 * transactions affecting the wallet since the requested block
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTransactions(final List<WalletTx> transactions) {
		this.transactions = transactions;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Catchup)) return false;
		final Catchup other = (Catchup)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$lastblock = this.getLastblock();
		final java.lang.Object other$lastblock = other.getLastblock();
		if (this$lastblock == null ? other$lastblock != null : !this$lastblock.equals(other$lastblock)) return false;
		final java.lang.Object this$transactions = this.getTransactions();
		final java.lang.Object other$transactions = other.getTransactions();
		if (this$transactions == null ? other$transactions != null : !this$transactions.equals(other$transactions)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Catchup;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $lastblock = this.getLastblock();
		result = result * PRIME + ($lastblock == null ? 43 : $lastblock.hashCode());
		final java.lang.Object $transactions = this.getTransactions();
		result = result * PRIME + ($transactions == null ? 43 : $transactions.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "Catchup(lastblock=" + this.getLastblock() + ", transactions=" + this.getTransactions() + ")";
	}
}