// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

public class Dependency extends Outpoint {
	
	/**
	 * output’s pubkey script encoded as hex
	 */
	String scriptPubKey;
	
	/**
	 * if the pubkey script was a script hash, this must be the corresponding redeem script
	 */
	String redeemScript;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Dependency() {
	}

	/**
	 * output’s pubkey script encoded as hex
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getScriptPubKey() {
		return this.scriptPubKey;
	}

	/**
	 * if the pubkey script was a script hash, this must be the corresponding redeem script
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getRedeemScript() {
		return this.redeemScript;
	}

	/**
	 * output’s pubkey script encoded as hex
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setScriptPubKey(final String scriptPubKey) {
		this.scriptPubKey = scriptPubKey;
	}

	/**
	 * if the pubkey script was a script hash, this must be the corresponding redeem script
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setRedeemScript(final String redeemScript) {
		this.redeemScript = redeemScript;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "Dependency(scriptPubKey=" + this.getScriptPubKey() + ", redeemScript=" + this.getRedeemScript() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Dependency)) return false;
		final Dependency other = (Dependency)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$scriptPubKey = this.getScriptPubKey();
		final java.lang.Object other$scriptPubKey = other.getScriptPubKey();
		if (this$scriptPubKey == null ? other$scriptPubKey != null : !this$scriptPubKey.equals(other$scriptPubKey)) return false;
		final java.lang.Object this$redeemScript = this.getRedeemScript();
		final java.lang.Object other$redeemScript = other.getRedeemScript();
		if (this$redeemScript == null ? other$redeemScript != null : !this$redeemScript.equals(other$redeemScript)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Dependency;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + super.hashCode();
		final java.lang.Object $scriptPubKey = this.getScriptPubKey();
		result = result * PRIME + ($scriptPubKey == null ? 43 : $scriptPubKey.hashCode());
		final java.lang.Object $redeemScript = this.getRedeemScript();
		result = result * PRIME + ($redeemScript == null ? 43 : $redeemScript.hashCode());
		return result;
	}
}