// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

import java.math.BigDecimal;

public class Info {
	private long version;
	private long protocolversion;
	private long walletversion;
	private BigDecimal balance;
	private long blocks;
	private long timeoffset;
	private long connections;
	private String proxy;
	private BigDecimal difficulty;
	private boolean testnet;
	private long keypoololdest;
	private long keypoolsize;
	private BigDecimal paytxfee;
	private BigDecimal relayfee;
	private String errors;
	private long unlocked_until;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Info() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getVersion() {
		return this.version;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getProtocolversion() {
		return this.protocolversion;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getWalletversion() {
		return this.walletversion;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public BigDecimal getBalance() {
		return this.balance;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getBlocks() {
		return this.blocks;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getTimeoffset() {
		return this.timeoffset;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getConnections() {
		return this.connections;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getProxy() {
		return this.proxy;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public BigDecimal getDifficulty() {
		return this.difficulty;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean isTestnet() {
		return this.testnet;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getKeypoololdest() {
		return this.keypoololdest;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getKeypoolsize() {
		return this.keypoolsize;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public BigDecimal getPaytxfee() {
		return this.paytxfee;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public BigDecimal getRelayfee() {
		return this.relayfee;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getErrors() {
		return this.errors;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getUnlocked_until() {
		return this.unlocked_until;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setVersion(final long version) {
		this.version = version;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setProtocolversion(final long protocolversion) {
		this.protocolversion = protocolversion;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setWalletversion(final long walletversion) {
		this.walletversion = walletversion;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setBalance(final BigDecimal balance) {
		this.balance = balance;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setBlocks(final long blocks) {
		this.blocks = blocks;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTimeoffset(final long timeoffset) {
		this.timeoffset = timeoffset;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setConnections(final long connections) {
		this.connections = connections;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setProxy(final String proxy) {
		this.proxy = proxy;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setDifficulty(final BigDecimal difficulty) {
		this.difficulty = difficulty;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTestnet(final boolean testnet) {
		this.testnet = testnet;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setKeypoololdest(final long keypoololdest) {
		this.keypoololdest = keypoololdest;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setKeypoolsize(final long keypoolsize) {
		this.keypoolsize = keypoolsize;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setPaytxfee(final BigDecimal paytxfee) {
		this.paytxfee = paytxfee;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setRelayfee(final BigDecimal relayfee) {
		this.relayfee = relayfee;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setErrors(final String errors) {
		this.errors = errors;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setUnlocked_until(final long unlocked_until) {
		this.unlocked_until = unlocked_until;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Info)) return false;
		final Info other = (Info)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (this.getVersion() != other.getVersion()) return false;
		if (this.getProtocolversion() != other.getProtocolversion()) return false;
		if (this.getWalletversion() != other.getWalletversion()) return false;
		final java.lang.Object this$balance = this.getBalance();
		final java.lang.Object other$balance = other.getBalance();
		if (this$balance == null ? other$balance != null : !this$balance.equals(other$balance)) return false;
		if (this.getBlocks() != other.getBlocks()) return false;
		if (this.getTimeoffset() != other.getTimeoffset()) return false;
		if (this.getConnections() != other.getConnections()) return false;
		final java.lang.Object this$proxy = this.getProxy();
		final java.lang.Object other$proxy = other.getProxy();
		if (this$proxy == null ? other$proxy != null : !this$proxy.equals(other$proxy)) return false;
		final java.lang.Object this$difficulty = this.getDifficulty();
		final java.lang.Object other$difficulty = other.getDifficulty();
		if (this$difficulty == null ? other$difficulty != null : !this$difficulty.equals(other$difficulty)) return false;
		if (this.isTestnet() != other.isTestnet()) return false;
		if (this.getKeypoololdest() != other.getKeypoololdest()) return false;
		if (this.getKeypoolsize() != other.getKeypoolsize()) return false;
		final java.lang.Object this$paytxfee = this.getPaytxfee();
		final java.lang.Object other$paytxfee = other.getPaytxfee();
		if (this$paytxfee == null ? other$paytxfee != null : !this$paytxfee.equals(other$paytxfee)) return false;
		final java.lang.Object this$relayfee = this.getRelayfee();
		final java.lang.Object other$relayfee = other.getRelayfee();
		if (this$relayfee == null ? other$relayfee != null : !this$relayfee.equals(other$relayfee)) return false;
		final java.lang.Object this$errors = this.getErrors();
		final java.lang.Object other$errors = other.getErrors();
		if (this$errors == null ? other$errors != null : !this$errors.equals(other$errors)) return false;
		if (this.getUnlocked_until() != other.getUnlocked_until()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Info;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final long $version = this.getVersion();
		result = result * PRIME + (int)($version >>> 32 ^ $version);
		final long $protocolversion = this.getProtocolversion();
		result = result * PRIME + (int)($protocolversion >>> 32 ^ $protocolversion);
		final long $walletversion = this.getWalletversion();
		result = result * PRIME + (int)($walletversion >>> 32 ^ $walletversion);
		final java.lang.Object $balance = this.getBalance();
		result = result * PRIME + ($balance == null ? 43 : $balance.hashCode());
		final long $blocks = this.getBlocks();
		result = result * PRIME + (int)($blocks >>> 32 ^ $blocks);
		final long $timeoffset = this.getTimeoffset();
		result = result * PRIME + (int)($timeoffset >>> 32 ^ $timeoffset);
		final long $connections = this.getConnections();
		result = result * PRIME + (int)($connections >>> 32 ^ $connections);
		final java.lang.Object $proxy = this.getProxy();
		result = result * PRIME + ($proxy == null ? 43 : $proxy.hashCode());
		final java.lang.Object $difficulty = this.getDifficulty();
		result = result * PRIME + ($difficulty == null ? 43 : $difficulty.hashCode());
		result = result * PRIME + (this.isTestnet() ? 79 : 97);
		final long $keypoololdest = this.getKeypoololdest();
		result = result * PRIME + (int)($keypoololdest >>> 32 ^ $keypoololdest);
		final long $keypoolsize = this.getKeypoolsize();
		result = result * PRIME + (int)($keypoolsize >>> 32 ^ $keypoolsize);
		final java.lang.Object $paytxfee = this.getPaytxfee();
		result = result * PRIME + ($paytxfee == null ? 43 : $paytxfee.hashCode());
		final java.lang.Object $relayfee = this.getRelayfee();
		result = result * PRIME + ($relayfee == null ? 43 : $relayfee.hashCode());
		final java.lang.Object $errors = this.getErrors();
		result = result * PRIME + ($errors == null ? 43 : $errors.hashCode());
		final long $unlocked_until = this.getUnlocked_until();
		result = result * PRIME + (int)($unlocked_until >>> 32 ^ $unlocked_until);
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "Info(version=" + this.getVersion() + ", protocolversion=" + this.getProtocolversion() + ", walletversion=" + this.getWalletversion() + ", balance=" + this.getBalance() + ", blocks=" + this.getBlocks() + ", timeoffset=" + this.getTimeoffset() + ", connections=" + this.getConnections() + ", proxy=" + this.getProxy() + ", difficulty=" + this.getDifficulty() + ", testnet=" + this.isTestnet() + ", keypoololdest=" + this.getKeypoololdest() + ", keypoolsize=" + this.getKeypoolsize() + ", paytxfee=" + this.getPaytxfee() + ", relayfee=" + this.getRelayfee() + ", errors=" + this.getErrors() + ", unlocked_until=" + this.getUnlocked_until() + ")";
	}
}