// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

/**
 * TODO implement locktime rules https://bitcoin.org/en/developer-guide#locktime_parsing_rules
 */
public class Locktime {
	protected long locktime;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Locktime() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getLocktime() {
		return this.locktime;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setLocktime(final long locktime) {
		this.locktime = locktime;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Locktime)) return false;
		final Locktime other = (Locktime)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (this.getLocktime() != other.getLocktime()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Locktime;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final long $locktime = this.getLocktime();
		result = result * PRIME + (int)($locktime >>> 32 ^ $locktime);
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "Locktime(locktime=" + this.getLocktime() + ")";
	}
}