// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

/**
 * @see <a href="https://bitcoin.org/en/developer-reference#getnettotals">getnettotals wiki</a>
 */
public class NetworkTotals {
	
	/**
	 * total number of bytes received since the rpc was last restarted
	 */
	long totalbytesrecv;
	
	/**
	 * total number of bytes sent since the rpc was last restarted
	 */
	long totalbytessent;
	
	/**
	 * system time (not rpc adjusted time)
	 */
	long timemillis;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public NetworkTotals() {
	}

	/**
	 * total number of bytes received since the rpc was last restarted
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getTotalbytesrecv() {
		return this.totalbytesrecv;
	}

	/**
	 * total number of bytes sent since the rpc was last restarted
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getTotalbytessent() {
		return this.totalbytessent;
	}

	/**
	 * system time (not rpc adjusted time)
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getTimemillis() {
		return this.timemillis;
	}

	/**
	 * total number of bytes received since the rpc was last restarted
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTotalbytesrecv(final long totalbytesrecv) {
		this.totalbytesrecv = totalbytesrecv;
	}

	/**
	 * total number of bytes sent since the rpc was last restarted
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTotalbytessent(final long totalbytessent) {
		this.totalbytessent = totalbytessent;
	}

	/**
	 * system time (not rpc adjusted time)
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTimemillis(final long timemillis) {
		this.timemillis = timemillis;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof NetworkTotals)) return false;
		final NetworkTotals other = (NetworkTotals)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (this.getTotalbytesrecv() != other.getTotalbytesrecv()) return false;
		if (this.getTotalbytessent() != other.getTotalbytessent()) return false;
		if (this.getTimemillis() != other.getTimemillis()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof NetworkTotals;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final long $totalbytesrecv = this.getTotalbytesrecv();
		result = result * PRIME + (int)($totalbytesrecv >>> 32 ^ $totalbytesrecv);
		final long $totalbytessent = this.getTotalbytessent();
		result = result * PRIME + (int)($totalbytessent >>> 32 ^ $totalbytessent);
		final long $timemillis = this.getTimemillis();
		result = result * PRIME + (int)($timemillis >>> 32 ^ $timemillis);
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "NetworkTotals(totalbytesrecv=" + this.getTotalbytesrecv() + ", totalbytessent=" + this.getTotalbytessent() + ", timemillis=" + this.getTimemillis() + ")";
	}
}