// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

import java.math.BigDecimal;
import java.util.HashSet;

public class NetworkInfo {
	long version;
	String subversion;
	long protocolversion = 70002;
	long localservices;
	long timeoffset;
	int connections;
	HashSet<Network> networks;
	BigDecimal relayfee;
	HashSet<LocalAddress> localaddresses;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public NetworkInfo() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getVersion() {
		return this.version;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getSubversion() {
		return this.subversion;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getProtocolversion() {
		return this.protocolversion;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getLocalservices() {
		return this.localservices;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getTimeoffset() {
		return this.timeoffset;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getConnections() {
		return this.connections;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public HashSet<Network> getNetworks() {
		return this.networks;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public BigDecimal getRelayfee() {
		return this.relayfee;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public HashSet<LocalAddress> getLocaladdresses() {
		return this.localaddresses;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setVersion(final long version) {
		this.version = version;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setSubversion(final String subversion) {
		this.subversion = subversion;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setProtocolversion(final long protocolversion) {
		this.protocolversion = protocolversion;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setLocalservices(final long localservices) {
		this.localservices = localservices;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTimeoffset(final long timeoffset) {
		this.timeoffset = timeoffset;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setConnections(final int connections) {
		this.connections = connections;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setNetworks(final HashSet<Network> networks) {
		this.networks = networks;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setRelayfee(final BigDecimal relayfee) {
		this.relayfee = relayfee;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setLocaladdresses(final HashSet<LocalAddress> localaddresses) {
		this.localaddresses = localaddresses;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof NetworkInfo)) return false;
		final NetworkInfo other = (NetworkInfo)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (this.getVersion() != other.getVersion()) return false;
		final java.lang.Object this$subversion = this.getSubversion();
		final java.lang.Object other$subversion = other.getSubversion();
		if (this$subversion == null ? other$subversion != null : !this$subversion.equals(other$subversion)) return false;
		if (this.getProtocolversion() != other.getProtocolversion()) return false;
		if (this.getLocalservices() != other.getLocalservices()) return false;
		if (this.getTimeoffset() != other.getTimeoffset()) return false;
		if (this.getConnections() != other.getConnections()) return false;
		final java.lang.Object this$networks = this.getNetworks();
		final java.lang.Object other$networks = other.getNetworks();
		if (this$networks == null ? other$networks != null : !this$networks.equals(other$networks)) return false;
		final java.lang.Object this$relayfee = this.getRelayfee();
		final java.lang.Object other$relayfee = other.getRelayfee();
		if (this$relayfee == null ? other$relayfee != null : !this$relayfee.equals(other$relayfee)) return false;
		final java.lang.Object this$localaddresses = this.getLocaladdresses();
		final java.lang.Object other$localaddresses = other.getLocaladdresses();
		if (this$localaddresses == null ? other$localaddresses != null : !this$localaddresses.equals(other$localaddresses)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof NetworkInfo;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final long $version = this.getVersion();
		result = result * PRIME + (int)($version >>> 32 ^ $version);
		final java.lang.Object $subversion = this.getSubversion();
		result = result * PRIME + ($subversion == null ? 43 : $subversion.hashCode());
		final long $protocolversion = this.getProtocolversion();
		result = result * PRIME + (int)($protocolversion >>> 32 ^ $protocolversion);
		final long $localservices = this.getLocalservices();
		result = result * PRIME + (int)($localservices >>> 32 ^ $localservices);
		final long $timeoffset = this.getTimeoffset();
		result = result * PRIME + (int)($timeoffset >>> 32 ^ $timeoffset);
		result = result * PRIME + this.getConnections();
		final java.lang.Object $networks = this.getNetworks();
		result = result * PRIME + ($networks == null ? 43 : $networks.hashCode());
		final java.lang.Object $relayfee = this.getRelayfee();
		result = result * PRIME + ($relayfee == null ? 43 : $relayfee.hashCode());
		final java.lang.Object $localaddresses = this.getLocaladdresses();
		result = result * PRIME + ($localaddresses == null ? 43 : $localaddresses.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "NetworkInfo(version=" + this.getVersion() + ", subversion=" + this.getSubversion() + ", protocolversion=" + this.getProtocolversion() + ", localservices=" + this.getLocalservices() + ", timeoffset=" + this.getTimeoffset() + ", connections=" + this.getConnections() + ", networks=" + this.getNetworks() + ", relayfee=" + this.getRelayfee() + ", localaddresses=" + this.getLocaladdresses() + ")";
	}
}