// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

public class Outpoint {
	
	/**
	 * txid of the outpoint in hex
	 */
	protected String txid;
	
	/**
	 * Output index number of the output
	 */
	protected int vout;

	/**
	 * txid of the outpoint in hex
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getTxid() {
		return this.txid;
	}

	/**
	 * Output index number of the output
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getVout() {
		return this.vout;
	}

	/**
	 * txid of the outpoint in hex
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTxid(final String txid) {
		this.txid = txid;
	}

	/**
	 * Output index number of the output
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setVout(final int vout) {
		this.vout = vout;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Outpoint)) return false;
		final Outpoint other = (Outpoint)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$txid = this.getTxid();
		final java.lang.Object other$txid = other.getTxid();
		if (this$txid == null ? other$txid != null : !this$txid.equals(other$txid)) return false;
		if (this.getVout() != other.getVout()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Outpoint;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $txid = this.getTxid();
		result = result * PRIME + ($txid == null ? 43 : $txid.hashCode());
		result = result * PRIME + this.getVout();
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "Outpoint(txid=" + this.getTxid() + ", vout=" + this.getVout() + ")";
	}

	@java.beans.ConstructorProperties({"txid", "vout"})
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Outpoint(final String txid, final int vout) {
		this.txid = txid;
		this.vout = vout;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Outpoint() {
	}
}