// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

import java.math.BigDecimal;
import java.util.List;

public class ReceivedByAddress {
    private BigDecimal amount;
    private long confirmations;
    private String address;
    private String account;
    boolean involvedWatchonly;
    List<String> txids;

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public ReceivedByAddress() {
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public BigDecimal getAmount() {
        return this.amount;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public long getConfirmations() {
        return this.confirmations;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getAccount() {
        return this.account;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean isInvolvedWatchonly() {
        return this.involvedWatchonly;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public List<String> getTxids() {
        return this.txids;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setConfirmations(final long confirmations) {
        this.confirmations = confirmations;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setAccount(final String account) {
        this.account = account;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setInvolvedWatchonly(final boolean involvedWatchonly) {
        this.involvedWatchonly = involvedWatchonly;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setTxids(final List<String> txids) {
        this.txids = txids;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ReceivedByAddress)) return false;
        final ReceivedByAddress other = (ReceivedByAddress)o;
        if (!other.canEqual((java.lang.Object)this)) return false;
        final java.lang.Object this$amount = this.getAmount();
        final java.lang.Object other$amount = other.getAmount();
        if (this$amount == null ? other$amount != null : !this$amount.equals(other$amount)) return false;
        if (this.getConfirmations() != other.getConfirmations()) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$account = this.getAccount();
        final java.lang.Object other$account = other.getAccount();
        if (this$account == null ? other$account != null : !this$account.equals(other$account)) return false;
        if (this.isInvolvedWatchonly() != other.isInvolvedWatchonly()) return false;
        final java.lang.Object this$txids = this.getTxids();
        final java.lang.Object other$txids = other.getTxids();
        if (this$txids == null ? other$txids != null : !this$txids.equals(other$txids)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ReceivedByAddress;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $amount = this.getAmount();
        result = result * PRIME + ($amount == null ? 43 : $amount.hashCode());
        final long $confirmations = this.getConfirmations();
        result = result * PRIME + (int)($confirmations >>> 32 ^ $confirmations);
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $account = this.getAccount();
        result = result * PRIME + ($account == null ? 43 : $account.hashCode());
        result = result * PRIME + (this.isInvolvedWatchonly() ? 79 : 97);
        final java.lang.Object $txids = this.getTxids();
        result = result * PRIME + ($txids == null ? 43 : $txids.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
        return "ReceivedByAddress(amount=" + this.getAmount() + ", confirmations=" + this.getConfirmations() + ", address=" + this.getAddress() + ", account=" + this.getAccount() + ", involvedWatchonly=" + this.isInvolvedWatchonly() + ", txids=" + this.getTxids() + ")";
    }
}