// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

/**
 * P2SH address and hex-encoded redeem script
 */
public class RedeemScript {
	
	/**
	 * P2SH address for this multisig redeem script
	 */
	String address;
	
	/**
	 * hex multisig redeem script
	 */
	String redeemScript;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public RedeemScript() {
	}

	/**
	 * P2SH address for this multisig redeem script
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getAddress() {
		return this.address;
	}

	/**
	 * hex multisig redeem script
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getRedeemScript() {
		return this.redeemScript;
	}

	/**
	 * P2SH address for this multisig redeem script
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setAddress(final String address) {
		this.address = address;
	}

	/**
	 * hex multisig redeem script
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setRedeemScript(final String redeemScript) {
		this.redeemScript = redeemScript;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof RedeemScript)) return false;
		final RedeemScript other = (RedeemScript)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$address = this.getAddress();
		final java.lang.Object other$address = other.getAddress();
		if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
		final java.lang.Object this$redeemScript = this.getRedeemScript();
		final java.lang.Object other$redeemScript = other.getRedeemScript();
		if (this$redeemScript == null ? other$redeemScript != null : !this$redeemScript.equals(other$redeemScript)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof RedeemScript;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $address = this.getAddress();
		result = result * PRIME + ($address == null ? 43 : $address.hashCode());
		final java.lang.Object $redeemScript = this.getRedeemScript();
		result = result * PRIME + ($redeemScript == null ? 43 : $redeemScript.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "RedeemScript(address=" + this.getAddress() + ", redeemScript=" + this.getRedeemScript() + ")";
	}
}