// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

public enum SigHash {
	ALL("ALL"),
	NONE("NONE"),
	SINGLE("SINGLE"),
	ALL_ANYONECANPAY("ALL|ANYONECANPAY"),
	NONE_ANYONECANPAY("NONE|ANYONECANPAY"),
	SINGLE_ANYONECANPAY("SINGLE|ANYONECANPAY");
	private final String value;

	/**
	 * Json Mapper directed to use the toString() value
	 */
	@Override
	public String toString() {
		return value;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	private SigHash(final String value) {
		this.value = value;
	}
}