// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

import java.util.ArrayList;

/**
 * Result of a <a href="https://bitcoin.org/en/developer-reference#decoderawtransaction">
 * decoderawtransaction</a> call
 */
public class Tx {
	
	/**
	 * transaction’s TXID encoded as hex in RPC byte order
	 */
	protected String txid;
	
	/**
	 * transaction format version number
	 */
	protected int version;
	
	/**
	 * @see locktime rules https://bitcoin.org/en/developer-guide#locktime_parsing_rules
	 */
	protected long locktime;
	
	/**
	 * Inputs being spent array, https://bitcoin.org/en/glossary/input
	 */
	protected ArrayList<Vin> vin;
	
	/**
	 * Outputs receiving funds, https://bitcoin.org/en/glossary/output
	 */
	protected ArrayList<Vout> vout;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Tx() {
	}

	/**
	 * transaction’s TXID encoded as hex in RPC byte order
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getTxid() {
		return this.txid;
	}

	/**
	 * transaction format version number
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getVersion() {
		return this.version;
	}

	/**
	 * @see locktime rules https://bitcoin.org/en/developer-guide#locktime_parsing_rules
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getLocktime() {
		return this.locktime;
	}

	/**
	 * Inputs being spent array, https://bitcoin.org/en/glossary/input
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public ArrayList<Vin> getVin() {
		return this.vin;
	}

	/**
	 * Outputs receiving funds, https://bitcoin.org/en/glossary/output
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public ArrayList<Vout> getVout() {
		return this.vout;
	}

	/**
	 * transaction’s TXID encoded as hex in RPC byte order
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTxid(final String txid) {
		this.txid = txid;
	}

	/**
	 * transaction format version number
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setVersion(final int version) {
		this.version = version;
	}

	/**
	 * @see locktime rules https://bitcoin.org/en/developer-guide#locktime_parsing_rules
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setLocktime(final long locktime) {
		this.locktime = locktime;
	}

	/**
	 * Inputs being spent array, https://bitcoin.org/en/glossary/input
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setVin(final ArrayList<Vin> vin) {
		this.vin = vin;
	}

	/**
	 * Outputs receiving funds, https://bitcoin.org/en/glossary/output
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setVout(final ArrayList<Vout> vout) {
		this.vout = vout;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Tx)) return false;
		final Tx other = (Tx)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$txid = this.getTxid();
		final java.lang.Object other$txid = other.getTxid();
		if (this$txid == null ? other$txid != null : !this$txid.equals(other$txid)) return false;
		if (this.getVersion() != other.getVersion()) return false;
		if (this.getLocktime() != other.getLocktime()) return false;
		final java.lang.Object this$vin = this.getVin();
		final java.lang.Object other$vin = other.getVin();
		if (this$vin == null ? other$vin != null : !this$vin.equals(other$vin)) return false;
		final java.lang.Object this$vout = this.getVout();
		final java.lang.Object other$vout = other.getVout();
		if (this$vout == null ? other$vout != null : !this$vout.equals(other$vout)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Tx;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $txid = this.getTxid();
		result = result * PRIME + ($txid == null ? 43 : $txid.hashCode());
		result = result * PRIME + this.getVersion();
		final long $locktime = this.getLocktime();
		result = result * PRIME + (int)($locktime >>> 32 ^ $locktime);
		final java.lang.Object $vin = this.getVin();
		result = result * PRIME + ($vin == null ? 43 : $vin.hashCode());
		final java.lang.Object $vout = this.getVout();
		result = result * PRIME + ($vout == null ? 43 : $vout.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "Tx(txid=" + this.getTxid() + ", version=" + this.getVersion() + ", locktime=" + this.getLocktime() + ", vin=" + this.getVin() + ", vout=" + this.getVout() + ")";
	}
}