// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

public class Vin {
	protected String txid;
	
	/**
	 * output index of the outpoint being spent, null? for coinbase
	 */
	protected Integer vout;
	
	/**
	 * describes the script of the input, null for coinbase
	 */
	protected ScriptSig scriptSig;
	
	/**
	 * similar to scriptSig's hex field, null for standard/non-coinbase txs
	 */
	protected String coinbase;
	
	/**
	 * input sequence number
	 */
	protected long sequence;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Vin() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getTxid() {
		return this.txid;
	}

	/**
	 * output index of the outpoint being spent, null? for coinbase
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Integer getVout() {
		return this.vout;
	}

	/**
	 * describes the script of the input, null for coinbase
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public ScriptSig getScriptSig() {
		return this.scriptSig;
	}

	/**
	 * similar to scriptSig's hex field, null for standard/non-coinbase txs
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public String getCoinbase() {
		return this.coinbase;
	}

	/**
	 * input sequence number
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getSequence() {
		return this.sequence;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTxid(final String txid) {
		this.txid = txid;
	}

	/**
	 * output index of the outpoint being spent, null? for coinbase
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setVout(final Integer vout) {
		this.vout = vout;
	}

	/**
	 * describes the script of the input, null for coinbase
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setScriptSig(final ScriptSig scriptSig) {
		this.scriptSig = scriptSig;
	}

	/**
	 * similar to scriptSig's hex field, null for standard/non-coinbase txs
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setCoinbase(final String coinbase) {
		this.coinbase = coinbase;
	}

	/**
	 * input sequence number
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setSequence(final long sequence) {
		this.sequence = sequence;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Vin)) return false;
		final Vin other = (Vin)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$txid = this.getTxid();
		final java.lang.Object other$txid = other.getTxid();
		if (this$txid == null ? other$txid != null : !this$txid.equals(other$txid)) return false;
		final java.lang.Object this$vout = this.getVout();
		final java.lang.Object other$vout = other.getVout();
		if (this$vout == null ? other$vout != null : !this$vout.equals(other$vout)) return false;
		final java.lang.Object this$scriptSig = this.getScriptSig();
		final java.lang.Object other$scriptSig = other.getScriptSig();
		if (this$scriptSig == null ? other$scriptSig != null : !this$scriptSig.equals(other$scriptSig)) return false;
		final java.lang.Object this$coinbase = this.getCoinbase();
		final java.lang.Object other$coinbase = other.getCoinbase();
		if (this$coinbase == null ? other$coinbase != null : !this$coinbase.equals(other$coinbase)) return false;
		if (this.getSequence() != other.getSequence()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Vin;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $txid = this.getTxid();
		result = result * PRIME + ($txid == null ? 43 : $txid.hashCode());
		final java.lang.Object $vout = this.getVout();
		result = result * PRIME + ($vout == null ? 43 : $vout.hashCode());
		final java.lang.Object $scriptSig = this.getScriptSig();
		result = result * PRIME + ($scriptSig == null ? 43 : $scriptSig.hashCode());
		final java.lang.Object $coinbase = this.getCoinbase();
		result = result * PRIME + ($coinbase == null ? 43 : $coinbase.hashCode());
		final long $sequence = this.getSequence();
		result = result * PRIME + (int)($sequence >>> 32 ^ $sequence);
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "Vin(txid=" + this.getTxid() + ", vout=" + this.getVout() + ", scriptSig=" + this.getScriptSig() + ", coinbase=" + this.getCoinbase() + ", sequence=" + this.getSequence() + ")";
	}
}