// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

import java.math.BigDecimal;

public class Vout {
	
	/**
	 * The number of bitcoins paid to this output. May be 0
	 */
	protected BigDecimal value;
	
	/**
	 * output index
	 */
	protected int n;
	protected ScriptPubKey scriptPubKey;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Vout() {
	}

	/**
	 * The number of bitcoins paid to this output. May be 0
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public BigDecimal getValue() {
		return this.value;
	}

	/**
	 * output index
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getN() {
		return this.n;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public ScriptPubKey getScriptPubKey() {
		return this.scriptPubKey;
	}

	/**
	 * The number of bitcoins paid to this output. May be 0
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setValue(final BigDecimal value) {
		this.value = value;
	}

	/**
	 * output index
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setN(final int n) {
		this.n = n;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setScriptPubKey(final ScriptPubKey scriptPubKey) {
		this.scriptPubKey = scriptPubKey;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Vout)) return false;
		final Vout other = (Vout)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$value = this.getValue();
		final java.lang.Object other$value = other.getValue();
		if (this$value == null ? other$value != null : !this$value.equals(other$value)) return false;
		if (this.getN() != other.getN()) return false;
		final java.lang.Object this$scriptPubKey = this.getScriptPubKey();
		final java.lang.Object other$scriptPubKey = other.getScriptPubKey();
		if (this$scriptPubKey == null ? other$scriptPubKey != null : !this$scriptPubKey.equals(other$scriptPubKey)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof Vout;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $value = this.getValue();
		result = result * PRIME + ($value == null ? 43 : $value.hashCode());
		result = result * PRIME + this.getN();
		final java.lang.Object $scriptPubKey = this.getScriptPubKey();
		result = result * PRIME + ($scriptPubKey == null ? 43 : $scriptPubKey.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "Vout(value=" + this.getValue() + ", n=" + this.getN() + ", scriptPubKey=" + this.getScriptPubKey() + ")";
	}
}