// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.data;

import java.math.BigDecimal;

public class WalletInfo {
	int walletversion;
	BigDecimal balance;
	BigDecimal unconfirmed_balance;
	BigDecimal immature_balance;
	long txcount;
	long keypoololdest;
	int keypoolsize;
	
	/**
	 * 0 of currently locked, or date in the future if currently unlocked, null if wallet is unencrypted.
	 */
	Long unlocked_until;

	/**
	 * @return null if wallet is unencrypted, 0 of locked, or date in the future if currently unlocked
	 */
	public Long getUnlocked_until() {
		return unlocked_until;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public WalletInfo() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getWalletversion() {
		return this.walletversion;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public BigDecimal getBalance() {
		return this.balance;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public BigDecimal getUnconfirmed_balance() {
		return this.unconfirmed_balance;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public BigDecimal getImmature_balance() {
		return this.immature_balance;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getTxcount() {
		return this.txcount;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public long getKeypoololdest() {
		return this.keypoololdest;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int getKeypoolsize() {
		return this.keypoolsize;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setWalletversion(final int walletversion) {
		this.walletversion = walletversion;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setBalance(final BigDecimal balance) {
		this.balance = balance;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setUnconfirmed_balance(final BigDecimal unconfirmed_balance) {
		this.unconfirmed_balance = unconfirmed_balance;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setImmature_balance(final BigDecimal immature_balance) {
		this.immature_balance = immature_balance;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setTxcount(final long txcount) {
		this.txcount = txcount;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setKeypoololdest(final long keypoololdest) {
		this.keypoololdest = keypoololdest;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setKeypoolsize(final int keypoolsize) {
		this.keypoolsize = keypoolsize;
	}

	/**
	 * 0 of currently locked, or date in the future if currently unlocked, null if wallet is unencrypted.
	 */
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public void setUnlocked_until(final Long unlocked_until) {
		this.unlocked_until = unlocked_until;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof WalletInfo)) return false;
		final WalletInfo other = (WalletInfo)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (this.getWalletversion() != other.getWalletversion()) return false;
		final java.lang.Object this$balance = this.getBalance();
		final java.lang.Object other$balance = other.getBalance();
		if (this$balance == null ? other$balance != null : !this$balance.equals(other$balance)) return false;
		final java.lang.Object this$unconfirmed_balance = this.getUnconfirmed_balance();
		final java.lang.Object other$unconfirmed_balance = other.getUnconfirmed_balance();
		if (this$unconfirmed_balance == null ? other$unconfirmed_balance != null : !this$unconfirmed_balance.equals(other$unconfirmed_balance)) return false;
		final java.lang.Object this$immature_balance = this.getImmature_balance();
		final java.lang.Object other$immature_balance = other.getImmature_balance();
		if (this$immature_balance == null ? other$immature_balance != null : !this$immature_balance.equals(other$immature_balance)) return false;
		if (this.getTxcount() != other.getTxcount()) return false;
		if (this.getKeypoololdest() != other.getKeypoololdest()) return false;
		if (this.getKeypoolsize() != other.getKeypoolsize()) return false;
		final java.lang.Object this$unlocked_until = this.getUnlocked_until();
		final java.lang.Object other$unlocked_until = other.getUnlocked_until();
		if (this$unlocked_until == null ? other$unlocked_until != null : !this$unlocked_until.equals(other$unlocked_until)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof WalletInfo;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		result = result * PRIME + this.getWalletversion();
		final java.lang.Object $balance = this.getBalance();
		result = result * PRIME + ($balance == null ? 43 : $balance.hashCode());
		final java.lang.Object $unconfirmed_balance = this.getUnconfirmed_balance();
		result = result * PRIME + ($unconfirmed_balance == null ? 43 : $unconfirmed_balance.hashCode());
		final java.lang.Object $immature_balance = this.getImmature_balance();
		result = result * PRIME + ($immature_balance == null ? 43 : $immature_balance.hashCode());
		final long $txcount = this.getTxcount();
		result = result * PRIME + (int)($txcount >>> 32 ^ $txcount);
		final long $keypoololdest = this.getKeypoololdest();
		result = result * PRIME + (int)($keypoololdest >>> 32 ^ $keypoololdest);
		result = result * PRIME + this.getKeypoolsize();
		final java.lang.Object $unlocked_until = this.getUnlocked_until();
		result = result * PRIME + ($unlocked_until == null ? 43 : $unlocked_until.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public java.lang.String toString() {
		return "WalletInfo(walletversion=" + this.getWalletversion() + ", balance=" + this.getBalance() + ", unconfirmed_balance=" + this.getUnconfirmed_balance() + ", immature_balance=" + this.getImmature_balance() + ", txcount=" + this.getTxcount() + ", keypoololdest=" + this.getKeypoololdest() + ", keypoolsize=" + this.getKeypoolsize() + ", unlocked_until=" + this.getUnlocked_until() + ")";
	}
}