// Generated by delombok at Wed Apr 20 02:15:35 MDT 2016
package org.fullnodej.exception;

/**
 * The fee was outside the tolerance bounds or zero. This may be a recoverable exception.
 */
public class FeeException extends RuntimeException {
	private static final long serialVersionUID = 2261317392820101615L;

	public static enum Type {
		ZERO_FEE,
		HIGH_FEE,
		REMOTE_EXCEPTION,
		OTHER,
		NOT_ENOUGH_DATA;

	}
	private final Type type;

	public FeeException(Type type) {
		this(type, type.name());
	}

	public FeeException(Type type, String message) {
		super(message);
		this.type = type;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public Type getType() {
		return this.type;
	}
}